const TYPES = {
  SERCH_VIDEOS: "SERCH_VIDEOS",
  SELECT_VIDEO: "SELECT_VIDEO",
  RETRIEVE_POPULARVIDEOS: "RETRIEVE_POPULARVIDEOS",
  SAVE_SEARCHTERMS: "SAVE_SEARCHTERMS",
  MANAGE_FAVOURITES: "MANAGE_FAVOURITES",
  SAVE_LASTWATCHED: "SAVE_LASTWATCHED",
  SAVE_LASTSEARCHES: "SAVE_LASTSEARCHES",
};

export { TYPES };
