const TYPES = {
  SERCH_VIDEOS: "SERCH_VIDEOS",
  SELECT_VIDEO: "SELECT_VIDEO",
  RETRIEVE_POPULARVIDEOS: "RETRIEVE_POPULARVIDEOS",
  SAVE_SEARCHTERMS: "SAVE_SEARCHTERMS",
  ADD_FAVOURITES: "ADD_FAVOURITES",
  MANAGE_FAVOURITES: "MANAGE_FAVOURITES",
};

export { TYPES };
